areaDetector/ADCore

ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileJPEG.cpp
ADApp/pluginSrc/NDFileMagick.cpp
ADApp/pluginSrc/NDFileNexus.cpp
ADApp/pluginSrc/NDFileTIFF.cpp
ADApp/pluginSrc/NDPluginFile.cpp

I reverted NDPluginFile.cpp on master to the R2-2 version, and created a new branch, file_locks, with the changes to NDPluginFile.cpp and all of the derived classes.

File locks

---

documentation/areaDetector.html

Slightly modified links and description

3rd party ref

---

ADApp/Db/NDFile_settings.req

Add LazyOpen and TempSuffix records to NDFile_settings.req.

Add LazyOpen and TempSuffix records

---

ADApp/pluginSrc/NDFileJPEG.cpp
ADApp/pluginSrc/NDFileTIFF.cpp

exclude irrelevant header

---

ADApp/op/edl/NDTransform.edl

This screen was updated by @ajf67d and is based on the equivalent medm screen.

Updated NDTransform.edl to work with the upgraded NDTransform plugin.

---

ADApp/pluginTests/Makefile
ADApp/pluginTests/TimeSeriesPluginWrapper.cpp
ADApp/pluginTests/TimeSeriesPluginWrapper.h
ADApp/pluginTests/test_NDPluginTimeSeries.cpp

Adding unittests to the new Time Series Plugin.
These are simple additions to the pluginTests dir and there are no changes to the TimeSeries plugin code.

Time Series Plugin Unittests

---

ADApp/Db/NDPluginBase.template
ADApp/Db/NDPluginBase_settings.req
ADApp/op/adl/NDPluginBase.adl
ADApp/pluginSrc/NDPluginDriver.cpp
ADApp/pluginSrc/NDPluginDriver.h
RELEASE.md

Fixed logic, I think it is ready to be tested and merged.

Change queue size

---

ADApp/pluginSrc/NDPluginOverlay.cpp
ADApp/pluginSrc/NDPluginROIStat.cpp

This patch fixes compilation with EPICS base 3.16 HEAD branch.

Add missing include files

---

ADApp/op/opi/ADBase.opi
ADApp/op/opi/ADSetup.opi

These are for https://github.com/areaDetector/ADAndor/pull/9.

OPI updates for serial number, firmware version and SDK version PVs.

---

ADApp/pluginTests/AsynPortClientContainer.cpp
ADApp/pluginTests/AsynPortClientContainer.h
ADApp/pluginTests/test_NDPluginOverlay.cpp

This adds the functionality requested in #227. I have updated the tests to pass the address to the write calls and added a test that uses address 1 to check it works.

Issue #227 - Add address option to AsynPortClientContainer

---

ADApp/pluginSrc/NDPluginFile.cpp
ADApp/pluginSrc/NDPluginFile.h

Added check for FilePluginClose attribute and close file if the value is 1.  This feature is used at DLS (@thomascobb) and we think it is a generally useful feature.

Implemented check for FilePluginClose attribute.

---

ADApp/pluginSrc/NDPosPlugin.cpp
ADApp/pluginSrc/NDPosPlugin.h

Fixed the memory leak in the NDPosPlugin. It leaked the filename on every write.

Fixed a leak in NDPosPlugin.

---

ADApp/ADSrc/Makefile
ADApp/commonDriverMakefile
ADApp/commonLibraryMakefile
ADApp/pluginSrc/Makefile
ADApp/pluginTests/Makefile

Built and tested the ADURL module from GraphicsMagick sources.

---

ADApp/op/edl/NDCircularBuff.edl

* POST_COUNT -> PostCount
* PRE_COUNT -> PreCount

Fix NDCircularBuff EDM screens for PV name changes

---

ADApp/pluginSrc/NDFileHDF5.cpp

This is useful for client applications that are monitoring the file using SWMR.

Ensure that the unique ID attribute is written out and flushed after all other attributes.

---

ADApp/op/edl/NDAttrPlot.edl
ADApp/op/edl/NDAttrPlot_Plot.edl
ADApp/op/edl/NDAttrPlot_Select.edl
ADApp/op/edl/NDAttrPlot_SelectSymbol.edl
ADApp/pluginSrc/NDPluginAttrPlot.cpp

Fixed NDPluginAttrPlot to start() after being created, and added some EDM screens for it

Ndattrplot

---

ADApp/pluginSrc/NDPluginFile.cpp

Previously Capture mode created NumCapture NDArrays using the "new" operator.
As NDArrays arrived it copied the data and attributes into these arrays.
This had several problems:
- The NDArrays were not allocated from the NDArrayPool, so memory limits were not enforced.
- Because they were not allocated from the NDArrayPool if they were passed to other functions
or plugins there would be problems with attempts to called NDArray::reserve() or release().
- The copy operation is inefficient and not a good idea.
The change was to simply allocate an array of NumCapture pointers.  As NDArrays arrive
their reference count is incremented with reserve() and the pointer is copied to the array.
After the files are written the cleanup routine now simply decrements the reference counter
with release(), …

Changed Capture mode. 

---

ADApp/pluginSrc/NDPluginFile.cpp

Also added error message for user.

Return error on attempt to Capture in NDFileModeSingle so Capture is cleared.

---

ADApp/pluginSrc/NDPluginROI.cpp

Adding paramName to more trace msgs for easier debugging.

Show paramName in writeInt32() trace msgs

---

ADApp/ADSrc/NDArrayPool.cpp

The current implementation of the NDArray allocation in combination with the freelist selection poses some severe disadvantages when using small and very large NDArrays at the same time.
This PR uses another strategy, which is better suited for such cases while keeping reallocations of similar sized NDArrays fast.
Best regards,
Michael

New NDArray allocation strategy

---

ADApp/ADSrc/NDArrayPool.cpp
ADApp/pluginSrc/NDPluginCodec.cpp

Fix issues with NDCodec

---

ADApp/ntndArrayConverterSrc/ntndArrayConverter.cpp
ADApp/pluginSrc/NDPluginCodec.cpp

Fixes #350

---

ADApp/pluginSrc/NDPluginCodec.cpp

remove class prefix

---

ADApp/commonDriverMakefile
ADApp/pluginSrc/NDFileHDF5Dataset.cpp
ADApp/pluginSrc/NDFileHDF5Dataset.h

Direct chunk write 2

---

ADApp/Db/NDFileHDF5.template
ADApp/op/edl/NDFileHDF5SWMRDetails.edl
ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5.h
documentation/NDFileHDF5.html

Up to date version of the original changes made by @ajgdls on https://github.com/dls-controls/ADCore/tree/manual-flush

Implemented the ability to force an HDF5 flush with new FlushNow record

---

ADApp/pluginSrc/NDPluginColorConvert.cpp

For issue #399 
Implemented a very simple linear interpolation for creating rgb values from a bayer colour filter array image, ignoring the pixels on the edges of the image.
This has been tested at DLS on a RHEL7 machine/ioc and it converts bayer to mono/rgb successfully, with a corresponding drop in network usage.

implemented conversion of bayer to Mono, RGB1, RGB2 and RGB3

---

ADApp/pluginSrc/NDFileHDF5.cpp

This PR is to address issue #398

Do not try to create the performance dataset when creating detector datasets.

---

ADApp/ntndArrayConverterSrc/ntndArrayConverter.cpp

Fixed bugs that caused crashes when new attributes were added and fields changed.

Fixed bugs that caused crashes when new attributes were added

---

ADApp/ADSrc/CCDMultiTrack.cpp
ADApp/ADSrc/CCDMultiTrack.h
ADApp/ADSrc/Makefile
ADApp/Db/CCDMultiTrack.template
ADApp/Db/CCDMultiTrack_settings.req
ADApp/Db/Makefile
ADApp/pluginSrc/Makefile
ADApp/pluginSrc/NDFileHDF5LayoutXML.cpp

This is typically used for spectroscopy applications.
Also, addressed issue #420, when used with VS build.

Added capability for CCD multi-track operation.

---

ADApp/pluginSrc/NDPluginCircularBuff.cpp

- A negative value will result in a segfault.
- Changing it while acquiring doesn't make sense, as it is used to allocate the ring buffer when the acquisition is started
- Change status message to something more meaningful when pre-count is 0

CircularBuff: Add extra checks when pre-count is set

---

ADApp/ntndArrayConverterSrc/ntndArrayConverter.cpp
ADApp/pluginSrc/NDFileHDF5.h
ADApp/pluginSrc/NDFileHDF5AttributeDataset.cpp
ADApp/pluginSrc/NDFileHDF5Dataset.cpp
ADApp/pluginSrc/NDFileHDF5Dataset.h
ADApp/pluginSrc/NDFileNexus.h
ADApp/pluginSrc/NDPluginAttrPlot.cpp
ADApp/pluginSrc/NDPluginFile.cpp
ADApp/pluginSrc/NDPluginFile.h
ADApp/pluginSrc/NDPosPlugin.h
ADApp/pluginTests/HDF5FileReader.cpp
ADApp/pluginTests/test_NDFileHDF5ExtraDimensions.cpp

Fixes for various build warnings from Clang on MacOS

Fix mac warnings
