Viewers/ImageJ/EPICS_areaDetector/EPICS_AD_Viewer.java

The ImageJ viewer newUniqueIdCallback inner class had a comment saying
it would prefer to do the synchronized notify in the monitorChanged
method.  This commit does that and removes the newUniqueId() method
which is no longer used.
The ImageJ viewer had three places in its updateImage() method
where it would assign to a variable the return value of
img.getProcessor().getPixels() but then immediately assign the return
value of epicsGet{Byte,Short,Float}Array() to the same variable.  The
value assigned to the variable from the img.getProcessor().getPixels()
call is overwritten and never used, therefore the first call and
assignment does nothing and can be removed.
The ImageJ viewer had dead code in its readProperties() method where it
assigned a value to the path variable and then checked …

viewers: simplify notify and remove dead code in ImageJ viewer

---

ADApp/pluginSrc/NDPluginFile.cpp

Was missing the VxWorks one as it takes only one argument but has the same symbol name as on Linux. Windows was already a special case.
This fixes an issue with #49 which prevented build on VxWorks.

Added a MKDIR macro to support mkdir on all platforms

---

iocBoot/hdf5_xml_layout_schema.xsd
iocBoot/new_txm_sample.xml
iocs/simDetectorIOC/iocBoot/iocSimDetector/hdf5_layout_demo.xml
iocs/simDetectorIOC/iocBoot/iocSimDetector/hdf5_layout_nexus.xml

This pull request is to resolve reported issue #58 by renaming the root tags as hdf5_layout instead of xml.  The schema has been updated, but there were no required code changes as the root tag is not used by name within the plugin.

Updated xml root tag from xml to hdf5_layout.

---

ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5.h

This update fixes the crash for issue #66 “ndattr_default=true” is not defined. The current logic is that if it is not defined it will not save them anywhere. 
This partly fixes issue #65. It should now save attributes under constant datasets. It does not save attributes under ndattribute datasets.

Hdf5 bugfix

---

ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5.h

Added support by creating datasets of chars with a dimension of size MAX_ATTRIBUTE_STRING_SIZE.  Added support for attribute datasets with rank of 2 if they are string type (2D datasets instead of usual 1D).
Fixes ticket #64

Added dataset support for String type NDAttributes (fixes ticket #64).

---

ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5LayoutXML.cpp
ADApp/pluginSrc/NDFileHDF5LayoutXML.h

Attribute datasets are now saved to the root location if no default dataset group is specified.  This can be overridden by setting a tag to false (auto_ndattr_default) in the hdf5_layout root element.
Resolves issue #66

 Save attribute datasets to the root location as a default (Resolves issue #66)

---

ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5.h
ADApp/pluginSrc/NDFileHDF5Layout.cpp
ADApp/pluginSrc/NDFileHDF5Layout.h

This resolves issue #68 
The following are added as NDAttributes (and stored using the usual rules and logic):
* NDArray.uniqueId as "NDArrayUniqueId"
* NDArray.timeStamp as "NDArrayTimeStamp"
* NDArray.epicsTS.secPastEpoch as "NDArrayEpicsTSSec"
* NDArray.epicsTS.nsec as "NDArrayEpicsTSnSec"
The following data is added as 1D attributes to all detector datasets with one element per image dimension:
* NDArray.ndims as "NDArrayNumDims" (special case: scaler integer, rather than 1D array)
* NDArray.dims[].offset as "NDArrayDimOffset"
* NDArray.dims[].binning as "NDArrayDimBinning"
* NDArray.dims[].reverse as "NDArrayDimReverse"

Default attributes from NDArrays stored in HDF5 files

---

ADApp/Db/NDFileHDF5.template
ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5.h

Introduced a new parameter NDAttributeChunk for setting chunking.  Updated
NDAttribute datasets to use unlimited maximum length and then increase the
size as required.  If the user stops the collection early then only
collected data is stored to the datasets.
This resolves issue #74.

Update NDAttribute datasets to increase in dimension as required Fix #74

---

ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5Dataset.cpp

Setting NumCapture=0 now allows capturing any number of frames.
Note that this feature is not supported in combination with using the extra
virtual dimensions.
When using this feature, the HDF5 istorek parameter (size of chunk index
binary search tree) is calculated using an estimated sensible number of
frames.
This fixes issue #72

HDF5 plugin support writing infinite number of frames

---

ADApp/pluginSrc/NDFileHDF5.cpp

Within the configureDims method a loop is performed to calculate chunking
parameters.  There are three user chunking parameters declared but the
loop is looping over the number of dims, this has been changed with a
comment to explain what the loop is doing.
This fixes issue #86

Only loop over 3 user chunking array elements to fix issue #86.

---

ADApp/pluginSrc/NDFileHDF5.cpp
iocs/simDetectorIOC/iocBoot/iocHDF5Test/test6.sh

The chunking dimensions calculation was not satisfactory in its previous
form.  Using the total number of dimensions didn't work when using extra
virtual dimensions, and my previous fix of hardcoding to 3 dims didn't
work when the writer was used in single mode (with only 2 dimensions of
array data).  The value used is now calculated using a combination of the
incoming array dimensions plus the mode of the writer.
The addition of iocHDF5Test/test6.sh reproduce the problem (and verify the fix - works for myself and @ajgdls).
This fixes #86

Further fix to the calculation of chunking dimensions #86.

---

ADApp/pluginSrc/NDFileHDF5.cpp

This is a small fix to ensure the HDF5 istorek parameter is set correctly.  Fixes issue #110.

Reorder the code for setting extradim to fix issue #110.

---

documentation/areaDetector.html

This change adds a section to the areaDetector HTML front-page where we can list and reference 3rd party supplied areaDetector drivers. I think it is useful for users to get a view of what cameras they can control with areaDetector - even the ones that we do not develop/support/distribute as part of the work in the areaDetector working group.
This was triggered by a request to include the ImXPAD detector driver by @oirled. This PR also include a reference to the XPAD detector.

3rd party software reference in documentation

---

ADApp/pluginTests/Makefile

The main problem we discussed earlier is when library A should use a system library in the normal default location, but library B exists in the system location but that version system should not be used for library B.  The problem is that if A_DIR is specified then the default system location can be searched first, and it will find the wrong version of library B.  This version of the Makefile allows defining BOOST but not BOOST_LIB, not defining HDF5_LIB, and defining SZIP but not SZIP_LIB.  If the _LIB definition is present it defines the _DIR and adds the library to PROD_LIBS.  If the _LIB definition is not present then it does not define the _DIR and adds the library to PROD_SYS_LIBS.  This prevents the system libraries from being added early in the library search path, and should fix …

Allow boost, hdf5, and sz to be SYS_LIBS 

---

ADApp/ADSrc/NDAttribute.cpp
ADApp/ADSrc/NDAttribute.h

NDAttribute::sourceType was never being set. Set it in constructor.  Add new NDAttrSourceUndefined enum; print NDAttribute::sourceType in NDAttribute::report().

NDAttribute::sourceType was never being set

---

ADApp/ADSrc/NDAttribute.cpp
ADApp/ADSrc/NDAttribute.h
ADApp/ntndArrayConverterSrc/ntndArrayConverter.cpp
ADApp/ntndArrayConverterSrc/ntndArrayConverter.h

A couple of issues on the conversion code between NDArrays and NTNDArrays regarding Attributes handling were fixed. Namely:
* Undefined attributes from NDArray to NTNDArray are now parsed correctly instead of throwing an exception.
* Source and source type of Attributes are now correctly parsed from NTNDArray to NDArray instead of being ignored.

Fixes to Attributes handling

---

ADApp/Db/NDStats.template
ADApp/pluginSrc/NDPluginStats.cpp
ADApp/pluginSrc/NDPluginStats.h

Hi,
I am submitting this as a suggestion to add a new waveform to the stats plugin to record the timestamp of each image in the timeseries buffer along with the actual values. This means that the data can be used later to match up with other values. This of course means the pImage->timeStamp value needs to be correct and hopefully set by hardware.
Any comments? Is there a better way to do this? 
S

Add timestamps waveform to timeseries

---

ADApp/Db/NDROIStatN.template
ADApp/pluginSrc/NDPluginROIStat.cpp
ADApp/pluginSrc/NDPluginROIStat.h

This pull request follows #140 and adds the time series of timestamps to the roistats plugin like the stats plugin.

[ENH] Added timeStamp to ROIStats timeseries data

---

iocBoot/commonPlugins.cmd

yySseq.db has been removed from synApps CALC, sseqRecord.db is identical replacement

functional replacement

---

ADApp/Db/NDArrayBase.template
ADApp/Db/NDPluginBase.template
ADApp/pluginSrc/NDPluginDriver.cpp

We've had this local patch at DLS for a while, it means that:
* all areaDetector drivers produce ArrayCallbacks by default. This is a change from the current behaviour, but we've never had a reason to turn ArrayCallbacks off apart from debugging.
* all areaDetector plugins can optionally be turned on by setting Enabled=1 in the substitution file. If this is not specified, the behaviour is the same as it is currently.
We've found this very useful, as we can deploy an IOC without having to go and enable manually every plugin and driver we need, and then rely on autosave to keep those changes for us.
Would this be acceptable?

Set EnableCallbacks from db, and set ArrayCallbacks to 1 by default

---

ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileJPEG.cpp
ADApp/pluginSrc/NDFileMagick.cpp
ADApp/pluginSrc/NDFileMagickStub.cpp
ADApp/pluginSrc/NDFileNetCDF.cpp
ADApp/pluginSrc/NDFileNexus.cpp
ADApp/pluginSrc/NDFileNull.cpp
ADApp/pluginSrc/NDFileTIFF.cpp
ADApp/pluginSrc/NDPluginAttribute.cpp
ADApp/pluginSrc/NDPluginCircularBuff.cpp
ADApp/pluginSrc/NDPluginColorConvert.cpp
ADApp/pluginSrc/NDPluginDriver.cpp
ADApp/pluginSrc/NDPluginDriver.h
ADApp/pluginSrc/NDPluginFFT.cpp
ADApp/pluginSrc/NDPluginOverlay.cpp
ADApp/pluginSrc/NDPluginProcess.cpp
ADApp/pluginSrc/NDPluginROI.cpp
ADApp/pluginSrc/NDPluginROIStat.cpp
ADApp/pluginSrc/NDPluginStats.cpp
ADApp/pluginSrc/NDPluginStdArrays.cpp
ADApp/pluginSrc/NDPluginTimeSeries.cpp
ADApp/pluginSrc/NDPluginTransform.cpp
ADApp/pluginTests/test_NDFileHDF5.cpp
ADApp/pluginTests/test_NDPluginCircularBuff.cpp
ADApp/pluginTests/test_NDPluginTimeSeries.cpp

This fixes #157 which was originally an issue with a race condition between the NDPluginDriver constructor and a thread being started in the constructor. Eventually we also found that there was a similar issue with the destructor. The two are somewhat related and this PR include fixes for both.
- Adding a locking mechanism to the NDPluginDriver constructor and thread so that a thread does not start running until the object is fully initialized.
- Switching NDPluginDriver from using the epics thread C interface to the epicsThreadRunable C++ class. This class has a feature to wait for a thread to exit which is required in the object destructor.
- Added NDPluginDriver::start() method which starts up the thread - and wait for it to signal that it is running. This method must be called outside …

Destructor race condition issue

---

ADApp/pluginTests/AsynPortClientContainer.cpp
ADApp/pluginTests/AsynPortClientContainer.h
ADApp/pluginTests/HDF5FileReader.cpp
ADApp/pluginTests/HDF5FileReader.h
ADApp/pluginTests/Makefile
ADApp/pluginTests/test_NDFileHDF5.cpp
ADApp/pluginTests/test_NDPluginTimeSeries.cpp

Replaced use of tr1::shared_ptr with boost::shared_ptr within the unittest framework which is based on boost. The boost::shared_ptr should be a 1:1 replacement for the tr1::shared_ptr and does not require OS dependent ifdefs to work...

Unittest made work on Darwin

---

RELEASE.md
Viewers/ImageJ/EPICS_areaDetector/EPICS_AD_Viewer.java

This is a minor fix that allows the ImageJ plugin to work with 1-D arrays (ny=0).  This is useful because the ImageJ Dynamic Profiler can then be used to plot the 1-D array.

Allow 1-D images, i.e. if ny=0 set ny=1

---

ADApp/pluginSrc/NDPluginTimeSeries.cpp
ADApp/pluginSrc/NDPluginTimeSeries.h

I was unable to reproduce a crash by changing the number of point in the time series plugin reported in #165.  However, I was able to crash it if the number of signals (first array dimension) in the driver callback was different from MaxSignals used in the array constructor.  This pull request fixes this problem.  I tested by changing the ADCSimDetector st.cmd to have MaxSignals be 1, 4, 8, 9.   The previous value was 8, which matches the size of the array from ADCSimDetector.  It now passes the tests, while previously it crashed.

Time series fix

---

ADApp/op/adl/ADAttrFile.adl
ADApp/op/adl/ADCollect.adl
ADApp/op/adl/ADReadout.adl
ADApp/op/opi/autoconvert/ADAttrFile.opi
ADApp/op/opi/autoconvert/ADCollect.opi
ADApp/op/ui/autoconvert/ADAttrFile.ui
ADApp/op/ui/autoconvert/ADCollect.ui
ADApp/op/ui/autoconvert/ADReadout.ui

note: ADExample simDetector.ui also needs this change (uses most but not all of ADCollect screen)

adjust text boxes so font is not tiny in autoconverted .ui files

---

ADApp/pluginSrc/NDPluginDriver.cpp

When changing queue size empty old queue first and release each NDArray in the queue; fixes memory leak.
This is a test done under the following conditions:
- simDetector with 1024x1024 Float64 arrays, .001 second AcquireTime=0.001. AcquirePeriod=0.01 (100 frames/s).
- Only NDPluginProcess running.  Doing RecursiveAverage, cannot keep up at 100 frames/s.
This was after acquiring some images and then setting Acquire=0 to stop acquisition.
epics> asynReport 10 SIM1
...
NDArrayPool:  
numBuffers=13, maxBuffers=0  
memorySize=109051904, maxMemory=0  
numFree=11  
There are 2 allocated NDArrays because the driver and plugin always keep the last one allocated.  This is normal.
This was after starting acquisition and changing NDPluginProcess queue size between 10 and 100 several times, and then …

Fix memory leak in NDArrayPool when changing queue szie

---

ADApp/ADSrc/asynNDArrayDriver.cpp

This fixes Valgrind "mismatched free/delete" error:
epics> ==5010== Mismatched free() / delete / delete []
==5010==    at 0x4A06016: operator delete(void*) (vg_replace_malloc.c:480)
==5010==    by 0x50E6746: asynNDArrayDriver::~asynNDArrayDriver() (asynNDArrayDriver.cpp:713)
==5010==    by 0x4C12CE8: medipixDetector::~medipixDetector() (medipixDetector.cpp:51)
==5010==    by 0x4C12A9F: medipixCleanup(void*) (medipixDetector.cpp:89)
==5010==    by 0x7092886: epicsExitCallAtExits (epicsExit.c:97)
==5010==    by 0x7092947: epicsExit (epicsExit.c:185)
==5010==    by 0x40804C: main (medipixDetectorAppMain.cpp:21)
==5010==  Address 0x7b4fd40 is 0 bytes inside a block of size 8 alloc'd
==5010==    at 0x4A057BB: calloc (vg_replace_malloc.c:593)
==5010==    by 0x50E6D35: …

Match calloc() with free() for asynNDArrayDriver::pArrays

---

ADApp/Db/NDFileHDF5.template
ADApp/Db/NDFileHDF5_settings.req
ADApp/op/adl/NDFileHDF5.adl
ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5.h
ADApp/pluginSrc/NDFileHDF5Layout.h

Allow writing NDAttributes of type NDAttrString as as 1-D array of type H5_C_S1[NumArrays] and size MAX_ATTRIBUTE_STRING_SIZE rather than a 2-D array of type H5T_NATIVE_CHAR[NumArrays, MAX_ATTRIBUTE_STRING_SIZE].  The default behavior is backwards compatbile, and there is a new EPICS PV that allows changing the behavior at run-time.  Fixes issue #176.

Allow writing NDAttributes of type NDAttrString as strings rather than char arrays

---

ADApp/pluginTests/Makefile
ci/configure.sh

Update the pluginTest/Makefile to use the new `WITH_*` macro to enable/disable 3rd party dependencies. 
Make the travis-ci configuration define WITH_HDF5=YES and WITH_BOOST=YES so that the HDF5 plugin and Boost-based unittest suite is built.
This fixes #206 (although the original issue was fixed already, this PR takes care of the secondary issue [mentioned in the thread](https://github.com/areaDetector/ADCore/issues/206#issuecomment-252762884) )

Travis tweaks

---

ADApp/commonDriverMakefile
ADApp/pluginSrc/NDPluginPva.cpp
ADApp/pluginSrc/NDPluginPva.h
documentation/NDPluginPva.html

This is an alternative solution to #221. With this change the plugin never calls `startPVAServer`, and it is left to the user to actually call it after `iocInit()` in the startup script. The documentation was updated to reflect this change. The `dbd` file that registers `startPVAServer` is included in the `commonDriverMakefile` file.

startPVAServer won't be called by the plugin anymore. Fixes #219

---

ADApp/ADSrc/NDAttribute.cpp
ADApp/ADSrc/NDAttribute.h
ADApp/ADSrc/NDAttributeList.cpp
ADApp/ADSrc/NDAttributeList.h
ADApp/ADSrc/paramAttribute.cpp
RELEASE.md
ci/build-synapps-deps.sh
ci/configure.sh

Changed NDAttribute files to use std::string for most of the string variables rather than char *.  Added new methods to set and get attributes of type NDAttrString using std::string rather than char *.
Removed the length limitation of MAX_ATTRIBUTE_STRING_SIZE in paramAttribute.cpp.  
Added trailing underscores to all private member variables for clarity.
These changes requiring using the master branch of asyn until R4-31 is released.  I have changed the files in ci/ to use git to get that branch and call it R4-31.

Change NDAttributes to use std::string

---

ADApp/Db/NDStats.template
ADApp/op/opi/NDStats.opi
ADApp/pluginSrc/NDPluginStats.cpp
ADApp/pluginSrc/NDPluginStats.h
RELEASE.md
documentation/NDPluginStats.html

I have implemented 3rd and 4th order image moments to calculate skewness and kurtosis according to:
https://en.wikipedia.org/wiki/Image_moment
I have also added eccentricity and orientation according to: https://imagej.nih.gov/ij/plugins/download/Moment_Calculator.java
Specifically these lines:
```
// Compute Orientation and Eccentricity
// source: Awcock, G.J., 1995, "Applied Image Processing", pp. 162-165
orientation = 0.5*Math.atan2((2.0*m11),(m20-m02));
orientation = orientation*180./Math.PI; //convert from radians to degrees
eccentricity = (Math.pow((m20-m02),2.0)+(4.0*m11*m11))/m00;
```
This is requirements for a profile monitor here at ESS, to avoid forking or code duplication, by putting it in a separate plugin, it would be nice to merge this.

Extend centroid calculations with image moments up to the fourth order

---

ADApp/pluginSrc/NDPluginDriver.cpp
ADApp/pluginSrc/NDPluginDriver.h

If blocking-callbacks are enabled in the port initialization, the callback thread will not be created, saving memory. In this case it is not allowed to disable blocking callbacks at runtime later (to allow runtime selection, blocking-callbacks must be set to 0 at initialization, so that the thread is created).

NDPluginDriver: Avoid creating the callback thread if blocking-callbacks are enabled at initialization.

---

ADApp/Db/NDPluginBase.template
ADApp/op/adl/NDCircularBuff.adl
ADApp/op/adl/NDColorConvert.adl
ADApp/op/adl/NDFFT.adl
ADApp/op/adl/NDFileHDF5.adl
ADApp/op/adl/NDFileJPEG.adl
ADApp/op/adl/NDFileMagick.adl
ADApp/op/adl/NDFileNetCDF.adl
ADApp/op/adl/NDFileNexus.adl
ADApp/op/adl/NDFileNull.adl
ADApp/op/adl/NDFileTIFF.adl
ADApp/op/adl/NDOverlay.adl
ADApp/op/adl/NDPluginAttribute.adl
ADApp/op/adl/NDPluginBase.adl
ADApp/op/adl/NDPluginTimeSeries.adl
ADApp/op/adl/NDPos.adl
ADApp/op/adl/NDProcess.adl
ADApp/op/adl/NDPva.adl
ADApp/op/adl/NDROI.adl
ADApp/op/adl/NDROIStat.adl
ADApp/op/adl/NDStdArrays.adl
ADApp/op/adl/NDTransform.adl
ADApp/pluginSrc/NDPluginDriver.cpp
ADApp/pluginSrc/NDPluginDriver.h
ADApp/pluginSrc/NDPluginFile.cpp
ADApp/pluginSrc/NDPluginFile.h
RELEASE.md
Viewers/ImageJ/EPICS_areaDetector/EPICS_AD_Viewer.java
documentation/pluginDoc.html

This pull request addresses issue #249 .
The NDPluginDriver base class now stores a pointer to the last NDArray it received.  There is a new ProcessPlugin parameter and record.  When the plugin receives the ProcessPlugin command it executes again with the previous NDArray input.  
All plugin medm screens are changed to be 25 pixels taller to display the new ProcessPlugin PV.
When a plugin reprocesses it does not change the UniqueId of the NDArray.  This resulted in the ImageJ viewer not displaying the image, because it was trigggered by the UniqueID PV in the NDPluginStdArrays plugin.  This was fixed by changing the ImageJ viewer to trigger on the ArrayCounter PV in the NDPluginStdArrays plugin instead of UniqueID.
Removed the parameter counting in NDPluginDriver, which is a nice feature …

Process plugin

---

ADApp/pluginSrc/NDPluginStats.cpp

* Restructured the checks on the denominators when calculating skew and kurtosis. This permits calculations on flat images, a single row or column.
* Check denominator when calculating eccentricity.

Bugfix imagemoments

---

.travis.yml
ADApp/pluginTests/Makefile
ADApp/pluginTests/plugin-test.cpp
ADApp/pluginTests/testingutilities.h

Here at SLAC we are using Boost 1.63.0 for our development and also static build for deployment.
When trying to build the tests we noticed some issues regarding the order of the libraries that are resolved with the changes on this pull request.
This PR also adds "sudo: required" to .travis.yml which is required to install packages.
See also PR at areaDetector repo: https://github.com/areaDetector/areaDetector/pull/23

Support for newer versions of Boost and static link of Boost Test.

---

ADApp/ADSrc/asynNDArrayDriver.cpp
ADApp/Db/NDArrayBase.template

I think it is good practice to allow user to set reasonable default values at iocInit. I know that most people probably use autosave and if available this fulfill their needs. However when writing startup scripts without autosave infrastructure this can greatly speed up the process of testing.
In principal I think that all setters should be macrofied, and default values should be removed from the cpp code. Although this a much bigger chunk of work and you have to know about implications this can have. In my opinion datatype is an essential setting which is not likely to change during run-time, hence it makes sense having a macro to allow it to be set once at iocInit. Currently this is the only one I am missing, but it's likely I will run in to more.
What is your take on this?

Allow datatype to be set at iocInit

---

ADApp/Db/NDFileHDF5.template
ADApp/Db/NDFileHDF5_settings.req
ADApp/op/adl/NDFileHDF5.adl
ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5.h

This PR when combined with https://github.com/areaDetector/ADSupport/pull/14, adds support of blosc filter.

add support of blosc filter

---

ADApp/pluginSrc/NDPluginROIStat.cpp

discovered by clang on darwin-x86

fix array delete

---

XML_schema/NDAttributes.xsd

Removes the `when` attribute from NDAttributes.xsd, the ND attributes XML Schema file.

refs #304: remove `when` attribute

---

ADApp/pluginSrc/NDFileJPEG.h

We're using jpeg version 6b, and jpeglib.h doesn't specify extern "C" when included by cplusplus code.
This adds ifdef __cplusplus  extern "C" around the include of jpeglib.h to avoid warnings and build errors.

Added ifdef __cplusplus extern C

---

ADApp/op/adl/ADSetup.adl

field is too narrow when converted to caQtDM .ui file

wider field for EPICS name PV

---

ADApp/commonDriverMakefile

see http://epics-pvdata.sourceforge.net/informative/developerGuide/developerGuide.html
qsrv allows clients to get, put and monitor V3 PVs (fields of EPICS DB records) via pvAccess.

build qsrv service into IOC

---

ADApp/pluginSrc/NDFileTIFF.cpp

The change allows saving 1D NDArray to TIFF file.
I'm working with NDArray with 1 dimension, think waveforms as data traces (i.e. ADC samples waveform). I seems one can not save a 1D NDArray to TIFF. I'm looking at this because I want to load TIFF file from processing plugin for subtracting background.
I've tested the changed code, on an IOC I'm working right now, and it allows me to save 1D array. After loading the same file from NDProcessing TIFF loading feature I can observe the background being subtracted as expected.
Would you accept such a change?
PS.
While writing this it got me thinking that maybe I could have two dimensions in my ADC waveform NDArrays, only for such purposes. Would that have any consequences on how the other plugins would behave, which now have no issues with …

Allow storing NDArrays with single dimension.

---

documentation/NDPluginROI.html

Noticed that issue while tried to configure the `maxThreads` parameter for detectors at the NSLS-II SMI beamline. The corresponding source code is: https://github.com/areaDetector/ADCore/blob/7fc9b3f1d5f7f81bfd11c552380d4af069b189ac/ADApp/pluginSrc/NDPluginROI.cpp#L367-L370.
I suspect similar update should be done for NDPluginStats.html, and some other files (leaving it up to the developers).

DOC: add missing maxThreads argument to NDROIConfigure

---

ADApp/Db/NDCircularBuff.template
ADApp/pluginSrc/NDArrayRing.cpp
ADApp/pluginSrc/NDFileTIFF.cpp
ADApp/pluginSrc/NDPluginCircularBuff.cpp
ADApp/pluginSrc/NDPluginCircularBuff.h
documentation/NDPluginCircularBuff.html

Hi Mark,
Here I am again suggesting same fixes. :)
1.  Fixing ND circular buffer so it flushes pre-trigger buffer immediately on software trigger. It is because in my case there might not be a sequential image after the trigger.
I added a PV which allows to regulate when buffer is flushed ($(P)$(R)FlushOnSoftTrg). By default the behavior is the same as before. If the parameter is set to 1=Immediately, pre buffer is flushed immediately on Software trigger arrival.
2. Fixing NDArrayRing. Currently buffer holder is deleted on clear request. That makes reuse of the NDArrayRing impossible if you need to clear NDArrayRing in between.
3. Small change in TIFF plugin which allows to read TIFFs generated in Photoshop or other editor which doesn't saves explicitly parameters with default value. …

Suggestions for NDCircularBuff

---

ADApp/ADSrc/NDArray.h
ADApp/ADSrc/NDArrayPool.cpp
ADApp/Db/NDCodec.template
ADApp/op/adl/NDCodec.adl
ADApp/op/edl/autoconvert/NDCodec.edl
ADApp/op/opi/autoconvert/NDCodec.opi
ADApp/op/ui/autoconvert/NDCodec.ui
ADApp/pluginSrc/NDPluginCodec.cpp
ADApp/pluginSrc/NDPluginCodec.h

Found and fixed a problem with NDPluginCodec.  It was not copying the NDAttributes from the input array to the output array.  Sometimes it worked: if the NDArray in the pool already had the attributes it worked, since they don't get removed.  But sometimes there were no attributes on the output array, including ColorMode. This led to problems in the ImageJ decompressor.  Changed alloc() so it adds all the metadata when the output array is created.
Changed errror handling from using fprintf to setting a string in a PV called CodecError.  This makes it easy for the user to see errors.  Added a new CodecStatus PV to show if the codec succeeded or failed. This required making some non-class functions into class methods so the errorMessage variable was accessible.

Codec improvements

---

ADApp/ADSrc/asynNDArrayDriver.cpp
ADApp/ADSrc/asynNDArrayDriver.h

This PR hopefully fixes #353. I have been running the tests [non-stop](https://stackoverflow.com/questions/6545763/how-can-i-rerun-a-program-with-gdb-until-a-segmentation-fault-occurs) for a few minutes now and no crashes were observed anymore.

Fix race condition on asynNDArrayDriver's destructor. Fix #353

---

ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5.h
ADApp/pluginSrc/NDFileHDF5Dataset.cpp
ADApp/pluginSrc/NDFileHDF5Dataset.h
ADApp/pluginTests/HDF5PluginWrapper.cpp
ADApp/pluginTests/HDF5PluginWrapper.h
ADApp/pluginTests/test_NDFileHDF5.cpp
ADApp/pluginTests/test_NDFileHDF5ExtraDimensions.cpp

Removed check for _UNITTEST_HDF5_.
Moved some private methods required for testing into protected scope.
Added testing methods in wrapper class.
Provided getters for internal dimensions.
Updated unit tests.
This PR is raised to address issues found within #381.  The defines have been removed, private methods that are required have been made protected and exposed through the test wrapper class, and getters have been created for all internal dimensions that need to be checked.

Improved unit tests to remove the need for define statements.

---

ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5AttributeDataset.cpp
ADApp/pluginSrc/NDFileHDF5Dataset.cpp
ADApp/pluginSrc/NDFileHDF5Dataset.h
ADApp/pluginSrc/NDFileHDF5LayoutXML.cpp

This fixes the HDF5 leaks that I have found using valgrind.
1) The NDFileHDF5Dataset objects were being allocated with "new" into this->detDataMap, but were never being deleted.
2) epicsStrDup was being used which allocates memory that is never freed.  I don't think it was necessary to use epicsStrDup.
3) The NDFileHDF5AttrDataset destructor was not freeing memory that it explicitly allocated.
4) There was no explicit destructor for NDFileHD5Dataset.  It is needed because it needs to free memory it explicitly allocated.

Fix memory leaks

---

.travis.yml
ci/install-packages.sh

Running unittest on Travis CI through valgrind for automatic memory checks.
This is a bit of a crude attempt to get memory/leak checks into the CI - consider this PR a discussion point for now.
Initial attempt does:
* Runs the unittest through valgrind, outputting report to a local text file.
* Prints (with tail) the last few lines of the valgrind report (i.e. the summary)
This obviously isn't the same as running an IOC - but is it good enough to get an idea if a new change (i.e. a PR) leaks?
Is the valgrind report useful in its current state? Should we do more to parse the resulting report? Add any other options to the valgrind command to show other details?

Travis: run unittest through valgrind

---

ADApp/pluginSrc/NDFileHDF5.cpp

This a change to fix memory leak in the HDF5 plugin, see #385.
Warning!
It appears that calling `H5close()` after `H5Fclose()` plugs the hole, but the core source of the the leak might still be at large!

fix memory leak by calling H5close() in NDFileHDF5::closeFile()

---

ADApp/pluginSrc/NDFileHDF5.cpp

After the recent introduction of Codec into NDArray, this filter does not compress anymore. This fix adapts to use the Codec property.

fix bitshuffle filter for NDArray codec property

---

ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5AttributeDataset.cpp
ADApp/pluginSrc/NDFileHDF5Dataset.cpp
ADApp/pluginSrc/NDFileHDF5Layout.cpp
ADApp/pluginSrc/NDFileHDF5LayoutXML.cpp

The initial fix for memory leaks that added a call to H5close() was not proper. It caused IOC crashes if two HDF5 plugin instances were used (https://github.com/areaDetector/ADCore/pull/390#issuecomment-479606488).
This set of changes removes the call to H5close() and adds localized resource freeing that should result in no memory leaks.
I added comments to the code paths that I've seen taken (`// HK OK`). Some other cases I did not test or verify (i.e. error branches) and for those the comment reads `// HK test`.
Someone needs to go over my changes and verify the correctness.

remove H5close call, introduce specific hdf5 object H5xclose calls

---

ADApp/commonDriverMakefile

I have been working on the R1-2 release of ADCompVision which adds support for saving videos from areaDetector cameras (timelapses, recordings, etc.) This requires opencv_video and opencv_videoio libraries to be linked during build, so these libs have been added to the ADCompVision call in commonDriverMakefile

Adding opencv_video and opencv_videoio as dependancy libs for ADCompVision

---

ADApp/Db/ADBase.template
ADApp/Db/NDArrayBase.template
ADApp/Db/NDFile.template
ADApp/Db/NDPluginBase.template
ADApp/Db/NDPosPlugin.template
RELEASE.md

After finding a high CPU rate when running a detector at 10KHz, it was found that changing the SCAN value for certain PVs would lower the CPU rate considerably. We have then added a macro for these PVs, so they could be easily changed, with a default value of "I/O Intr" so these changes would have no effect on others.
Refs #416

Set scan rate

---

ADApp/pluginSrc/NDFileHDF5.cpp
ADApp/pluginSrc/NDFileHDF5.h
XML_schema/hdf5_xml_layout_schema.xsd
docs/ADCore/NDFileHDF5.rst

This fixes #433.
I discovered that attDataMap was actually not being used.  Rather this list was used instead:
```
std::list<NDFileHDF5AttributeDataset*> attrList;
```
I renamed attDataMap to constDsetMap.  It contains all the hid_t for each of the constant datasets.  All of these datasets are now closed in CloseFile().
This eliminates the error messages.

Fix problem with not closing constant datasets

---

ADApp/ADSrc/ADDriver.cpp
ADApp/ADSrc/ADDriver.h

This PR addresses issue #448.
It does the following:
- Adds a new bool member variable `deviceIsConnected` to ADDriver.
- Initializes `deviceIsConnected` to `true` in the ADDriver constructor.
- Adds the `ADDriver::connect()` method.  This method looks at the value of `deviceIsConnected`.  If it is `true` then it calls `asynNDArrayDriver::connect()`, which ultimately that calls `asynPortDriver::connect()`.  That method calls `pasynManager->exceptionConnect()`.  This method is needed to prevent asynManager from autoconnecting to the driver when `deviceIsConnected` is `false`.
Real drivers can now signal that they have failed to connect to hardware, and thus set the driver to the `Disconnected` state by doing the following if hardware initialization fails, typically in their constructor:
- …

Improve disconnect

---

ADApp/commonDriverMakefile

This is needed when configured with `BOOST_EXTERNAL=YES`.
BTW with this fix ADSupport and ADCore built fine on MacOS using the default EXAMPLE_CONFIG_SITE.local (plus my own Boost). It also built fine using the system version of Boost that apparently comes with Apple XCode, which I wasn't immediately aware of. The only difference needed between EXAMPLE_CONFIG_SITE.local and a replacement for EXAMPLE_CONFIG_SITE.local.darwin-x86 would appear to be to drop the ARAVIS and GLIB definitions.

Set boost_system_DIR to find libboost_system

---

ADApp/pluginSrc/NDPluginPva.cpp

Starting with the next epics 7 release pvDatabase.cpp will no longer have any destroy methods.
With this change NDPluginPva will not build unless it's destroy methods are removed.
Note that for at least the last couple of epics7 releases pvDatabase.cpp has only had empty destroy methods.
Thus even with this change to NDPluginPva, ADCore will still build for at least the last couple of epics7 releases.

remove destroy

---

ADApp/Db/NDStats.template
ADApp/pluginSrc/NDPluginStats.cpp
ADApp/pluginSrc/NDPluginStats.h
documentation/NDPluginStats.html

Provides access to image pixel value at cursor position.
This enhancement and pull request suggested by colleague and EPICS mentor, Matt Pearson.
Added forward links to CursorX and CursorY to assure cursor value is updated when cursor changes.

Added cursor value computation to ND Stats plugin.

---

ADApp/pluginSrc/NDFileHDF5.cpp

The size passed to H5Tset_size() is supposed to include the trailing null character.  The current code is not doing that.  This results in error messages from the HDF5 library if a zero length string is passed.  The file structure is also not correct, the string data should include the trailing null character.
This fixes issue #460.

Include trailing null in size passed to H5Tset_size()

---

ADApp/Db/NDFile.template
ADApp/pluginSrc/NDPluginFile.cpp

I was having issues with full filenames being truncated due to the full filename being limited to the same size to the filename and filepath components.
This is a minimal change which increases the size of the full filename compared to the filename and filepath components. NDFileNexus.cpp already does something similar, but has a fixed format.
I'm not sure if the factor should be 3*MAX_FILENAME_LEN instead to account for possible extra characters in the file template on top of the substitution (although this will be slightly less than 256 characters depending on the formatting).

Make full filename large enough for filename and filepath components

---

ADApp/ADSrc/myAttributeFunctions.cpp

Fix a potential memory leak situation (in case of an unknown parameter).
(found by Sonar/cppcheck)

Fix potential memory leak (for unknown parameter)

---

ADApp/ntndArrayConverterSrc/ntndArrayConverter.cpp

When converting from an NDArray there is a conversion from using the EPICS epoch to Posix.
This change makes the conversion back to an NDArray consistent by converting back to EPICS time.

Convert back to EPICS epoch when creating NDArray in NTNDArrayConverter

---

ADApp/pluginSrc/NDFileHDF5AttributeDataset.cpp

This simplfies visualisation and plotting of these datasets as part of our hardware triggered scanning framework. With this change, extra dims will be added to match the shape of a scan, but it won't additionally pad the dimensions by an extra two to match (frame, height, width) detector datasets.
I am happy to make this a config option if it is neccesary to retain to the current behaviour.
cc @ajgdls

Removed unnecessary creation of 1x1 dimensions

---

ADApp/ADSrc/CCDMultiTrack.cpp

areaDetector uses 0-based pixel indexes - when I wrote this I had assumed 1-based indexes.
Consequently, I have inappropriate range checks.

Corrected index misunderstanding.

---

ADApp/commonDriverMakefile

Goes along with https://github.com/areaDetector/areaDetector/pull/73. Adds conditional where if RECCASTER is defined in configure/RELEASE_PRODS.local, we include the reccaster dbd and link against the reccaster libarary.

Adding optional reccaster support module to commonDriverMakefile

---

iocBoot/EXAMPLE_commonPlugins.cmd

Adding additional optional line to the example common plugins file that references the new `*.req` file created for the `ffmpegServer` plugin in https://github.com/areaDetector/ffmpegServer/pull/30

Add ffmpegServer req file location to req file path

---

iocBoot/EXAMPLE_commonPlugins.cmd

Uncommented NDPluginPva plugin. This is should be used routinely instead of the Image plugin.

Uncommented NDPluginPva plugin

---

ADApp/pluginSrc/NDFileNexus.cpp

This follows what is done in other `NDPluginFile` subclasses, like `NDFileJPEG`. Without it, the value of `{P}{R}PluginType_RBV` for the Nexus plugin is the more general string `NDPluginFile`, while the other file plugins show their specific plugin name.

Fix PluginType string for NDFileNexus plugin

---

.gitignore
ADApp/pluginSrc/NDFileHDF5.cpp

- use hsize_t for internal variables
- cast to (unsigned long long) and use "%llu" as printf conversion specification
Newer HDF5 provides macros for the specifier (e.g. PRIuHSIZE) but v1.10 in ADSupport doesn't, so casting to the widest type seems the best portable way to handle this.

Fix for changed hsize_t in HDF5 v1.14

---

.github/workflows/ci-scripts.yml
ADApp/pluginSrc/Makefile
ADApp/pluginSrc/NDFileHDF5AttributeDataset.h
ADApp/pluginSrc/NDFileHDF5Dataset.h
ADApp/pluginSrc/NDPluginAttrPlot.h
ADApp/pluginTests/Makefile

A couple of somewhat related build fixes.
For my Linux builds I use `-fvisibility=hidden -fvisibility-inlines-hidden` to catch dllimport/export errors.  This is stricter than MSVC.  Which is why the lack of `NDPLUGIN_API` on `class NDFileHDF5Dataset` has not been fatal so far.  However, I think this omission was not intentional, and adding this as a CI check should prevent repeats.
The main issue is that `libADTestUtility` has no API macros at all.  For the time being this can be handled by only linking a static version.
Is `ADTestUtility` intended for external use?
If not, then eg. changing `LIBRARY=` to `TEST_LIBRARY=` will prevent it from being installed.  Otherwise, it needs an `*API.h` and added decorations.
The last change is to omit `-DH5_NO_DEPRECATED_SYMBOLS`.  I think this makes …

Fixup build with deb12

---

ADApp/ADSrc/NDArray.cpp
ADApp/ADSrc/NDArray.h
ADApp/ADSrc/NDArrayPool.cpp

See issue https://github.com/areaDetector/ADCore/issues/487

Provide a way to override memory allocator for frames

---

ADApp/ADSrc/Makefile
ADApp/pluginSrc/Makefile

Mingw still generates multiple definitions of _Unwind_Resume.

LIBXML_STATIC needs to be defined in ADSrc for mingw static builds.

---

ADApp/ADSrc/NDAttribute.cpp
ADApp/ADSrc/NDAttribute.h
ADApp/ADSrc/asynNDArrayDriver.cpp

In relation to issue #478 
Adds NDAttributeConst with the corresponding string "CONST" to the list of acceptable NDAttribute types. If type="CONST" in an attributes XML file, a base NDAttribute with source as the value is added.

Add Constant NDAttributes

---

ADApp/ADSrc/asynNDArrayDriver.cpp

closes #502 @coretl Tested against the example XML from ADCore/ADApp/ADSrc/asynNDArrayDriver.cpp

Support XML string and file path for NDAttributesFile

---

ADApp/op/bob/sim_cam_image.bob

This BOB screen (for CSS Studio phoebus) could support the PVA1:Image from any area detector.  The _more ..._ pop-up menu has the `simDetector.bob` screen as the first item.  (Can this be generalized?)
Call this screen with two macros:
macro  | description  | example
---- | ---- | ----
`P`      | IOC prefix   | `ad:`
`R`      | cam module   | `cam1: `
example:

add BOB screen for ADSimDetector PVA image

---

docs/ADCore/NDPluginDriver.rst

Based on
https://github.com/areaDetector/ADCore/blob/7debeba5c6a3840460fb592d32c6976d0c4d94ff/ADApp/Db/NDPluginBase.template#L300-L308V

Fix typo in SortMode mode selection.

---

ADApp/Db/NDROIStat.template
ADApp/pluginSrc/NDPluginROIStat.cpp
ADApp/pluginSrc/NDPluginROIStat.h
docs/ADCore/NDPluginROIStat.rst

This adds the ability to clear the time series data without also starting acquisition. This can be useful when the use of the time series capture is intermittent or on-demand, and we do not always want the prior data in the waveform.

NDPluginROIStat: Clear the time series data without also starting acquisition

---

ADApp/ADSrc/myAttributeFunctions.cpp
ADApp/pluginSrc/NDFileTIFF.cpp

This PR does 2 things:
- Modifies myAttributeFunctions.cpp to generate attributes of all numeric datatypes.  This allows thorough testing of the TIFF plugin and other applications that handle NDAttributes.
- Fixes the TIFF plugin to handle all numeric attribute datatypes correctly.  Signed and unsigned integers are handled separately.  All integer types are converted to 64-bits before being converted to ASCII.
A new attribute XML file was added to simDetector to generate an instance of each attribute numeric datatype.
https://github.com/areaDetector/ADSimDetector/blob/master/iocs/simDetectorIOC/iocBoot/iocSimDetector/testAttributeDataTypes.xml
I tested ADSimDetector using that XML file.  
I printed out the values of the NDArray attributes:
```
epics> asynReport 20 SIM1
SIM1 multiDevice:No …
```

Fix attribute datatypes in TIFF plugin

---

docs/ADCore/NDPluginCodec.rst

Missing '_RBV', based on
https://github.com/areaDetector/ADCore/blob/94414af0d3fbbc3acacaaa7a73b5b8fbc68b907b/ADApp/Db/NDCodec.template#L67

Fix typo in NDCodecCompressor record name.

---

ADApp/pluginSrc/NDFileNexus.cpp

HI! We stumbled upon this when trying to add vector options to NDAttrDataType_t.
Regardless if vector options are actually going to be added, when NDAttrUndefined was moved to the 21th position of NDAttrDataType_t it collided with NX_UINT8 in NDFileNexus.cpp:663:
```
../ADApp/pluginSrc/NDFileNexus.cpp: In member function 'void NDFileNexus::constTextToDataType(char*, int, void*)':
../ADApp/pluginSrc/NDFileNexus.cpp:726:5: error: duplicate case value
case NDAttrUndefined:
^~~~
../ADApp/pluginSrc/NDFileNexus.cpp:681:5: note: previously used here
case NX_UINT8:
^~~~
```
Since that case condition actually does nothing but fall to the default case, we thought it would be healthy to remove it.

Remove comparing NexusDataType codes with NDDataTypeCodes

---

RELEASE.md
docs/ADCore/NDPluginPva.rst

The cars.uchicago.edu areaDetector URL currently redirects to the GitHub areaDetector repository instead of the previously provided page. Update the URL so that it is consistent with the existing text.
Accessing NTNDArray link gives a 404 on the other hand. Update it to the current PVAccess documentation.

Update URL of legacy pre-built artifacts and NTNDArray specification

---

RELEASE.md

The newline between list items and subheaders stopped being added in version R3-12. While GitHub renders this without issue, it broke read-the-docs, which stopped emitting headers and instead inserted the raw text (with '#' characters) as part of the previous list item.

Fix formatting of HTML release notes.

---

docs/ADCore/NDPluginDriver.rst

In commit 1569c4dd (Removed numParams and added maxThreads to constructor; removed doNDArrayCallbacks method, use NDPluginDriver::endProcessCallbacks instead; minor fix to asynPrint calls, 2017-03-23), doNDArrayCallbacks was renamed to endProcessCallbacks in NDPluginDriver, but its mentions in the "Sorting of output NDArrays" section weren't updated accordingly. Fix that.

Mention correct method in array sorting docs

---

ADApp/Db/NDFileHDF5.template
docs/ADCore/ADDriver.rst
docs/ADCore/NDArray.rst
docs/ADCore/NDFileHDF5.rst
docs/ADCore/NDPluginGather.rst

While taking a look at the available PVs on the ADDriver, NDArray, and HDF5 plugin pages, I found some inconsistencies in the documentation, mostly typos in PV names, and some missing records.
For the missing records, I've written a quite generic description. Feel free to propose a better description line for each of them.
I haven't gone through all pages, so there might be other inconsistencies around.
As always, I recommend reviewing this patch series commit-wise.

Fix inconsistencies in the documentation of some records

---

ADApp/Db/NDROIStat8.template

This is needed to fix a bug where multiple records with the same name were created.
Fix #546

Use R macro to distinguish between different ROIs in NDROIStat8.
